# Site settings
title: pmcgrath 
email: pmcgrath@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Various tech tidbits that I want to record. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: p_mc_grath
github_username:  pmcgrath

# Build settings
markdown: redcarpet             # So we can use fences code blocks
permalink: /:title              # So title alone is used for the link


fenced_code_blocks: true
