# Site settings
title: pmcgrath 
email: pat@pmcgrath.net
description: > # this means to ignore newlines until "baseurl:"
  Various tech tidbits that I want to record. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pmcgrath.github.io" # the base hostname & protocol for your site
twitter_username: p_mc_grath
github_username:  pmcgrath

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
permalink: /:title              # So title alone is used for the link
